#ifndef __USE_CONFIG
#define __USE_CONFIG


#define BOOTLOADER_VERSION "STM32F103VET6_BOOTLOADER_V_10_20190908"
#define APPLICATION_VERSION "STM32F103VET6_APPLICATION_V_11_20191007"


//#define BOOTLOADER
#define APPLICATION


//#define  USART1_DEBUG
//#define  USART2_DEBUG
//#define  USART3_DEBUG
//#define  UART4_DEBUG
#define  UART5_DEBUG


#endif

